import { Property } from './types';

export const DUMMY_PROPERTIES: Property[] = [
  {
    id: '1',
    title: 'Moderna Casa en City Bell',
    price: 320000,
    currency: 'USD',
    operation: 'Venta',
    type: 'Casa',
    neighborhood: 'City Bell',
    address: 'Calle 473 bis e/ 14 y 15',
    beds: 4,
    baths: 3,
    m2: 250,
    description: 'Espectacular propiedad de diseño moderno con amplios ventanales y jardin parquizado. Piscina climatizada y quincho.',
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=1200'],
    lat: -34.8715,
    lng: -58.0445,
    amenities: ['Piscina', 'Quincho', 'Cochera', 'Parrilla'],
    active: true,
    featured: true
  },
  {
    id: '2',
    title: 'Departamento Lujo Centro',
    price: 185000,
    currency: 'USD',
    operation: 'Venta',
    type: 'Departamento',
    neighborhood: 'Centro',
    address: 'Av. 7 y 50',
    beds: 2,
    baths: 2,
    m2: 95,
    description: 'Semipiso al frente con balcon corrido. Vistas panoramicas a la plaza Moreno.',
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=1200'],
    lat: -34.9215,
    lng: -57.9545,
    amenities: ['SUM', 'Seguridad', 'Balcón'],
    active: true,
    featured: false
  },
  {
    id: '3',
    title: 'PH Estilo Industrial',
    price: 125000,
    currency: 'USD',
    operation: 'Venta',
    type: 'PH',
    neighborhood: 'Tolosa',
    address: 'Calle 528 y 7',
    beds: 3,
    baths: 1,
    m2: 120,
    description: 'Reciclado a nuevo con estilo industrial. Techos altos, vigas a la vista y patio interno.',
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1200'],
    lat: -34.8985,
    lng: -57.9745,
    amenities: ['Patio', 'Parrilla'],
    active: true,
    featured: false
  },
  {
    id: '4',
    title: 'Casa Quinta Familiar',
    price: 550000,
    currency: 'ARS',
    operation: 'Alquiler',
    type: 'Casa',
    neighborhood: 'Villa Elisa',
    address: 'Camino Gral Belgrano y 411',
    beds: 5,
    baths: 4,
    m2: 1500,
    description: 'Amplia quinta para eventos o vivienda familiar. Gran arboleda y casa de huespedes.',
    images: ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&q=80&w=1200'],
    lat: -34.8415,
    lng: -58.0745,
    amenities: ['Cancha de Tenis', 'Piscina', 'Jardín'],
    active: true,
    featured: true
  },
  {
    id: '5',
    title: 'Lote en Barrio Cerrado',
    price: 75000,
    currency: 'USD',
    operation: 'Venta',
    type: 'Lote',
    neighborhood: 'Los Hornos',
    address: 'Calle 66 y 167',
    beds: 0,
    baths: 0,
    m2: 600,
    description: 'Excelente lote central en barrio privado con todos los servicios subterraneos.',
    images: ['https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=1200'],
    lat: -34.9515,
    lng: -57.9945,
    amenities: ['Seguridad', 'Club House'],
    active: true,
    featured: false
  },
  {
    id: '6',
    title: 'Departamento con Balcon',
    price: 85000,
    currency: 'USD',
    operation: 'Venta',
    type: 'Departamento',
    neighborhood: 'Villa Elvira',
    address: 'Calle 1 y 80',
    beds: 1,
    baths: 1,
    m2: 45,
    description: 'Ideal inversion. Departamento a estrenar en zona de rapido crecimiento.',
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=1200'],
    lat: -34.9415,
    lng: -57.9345,
    amenities: ['Balcón', 'Ascensor'],
    active: true,
    featured: false
  },
  {
    id: '7',
    title: 'Local Comercial Estrategico',
    price: 1500,
    currency: 'USD',
    operation: 'Alquiler',
    type: 'Local',
    neighborhood: 'Ensenada',
    address: 'La Merced y Horacio Cestino',
    beds: 0,
    baths: 1,
    m2: 80,
    description: 'Gran vidriera en esquina. Doble altura. Apto todo destino comercial.',
    images: ['https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80&w=1200'],
    lat: -34.8515,
    lng: -57.9045,
    amenities: ['Aire Acondicionado', 'Vidriera'],
    active: true,
    featured: false
  },
  {
    id: '8',
    title: 'Casa Ph Tolosa',
    price: 110000,
    currency: 'USD',
    operation: 'Venta',
    type: 'PH',
    neighborhood: 'Tolosa',
    address: 'Calle 2 e/ 530 y 531',
    beds: 2,
    baths: 1,
    m2: 85,
    description: 'Casa en PH con entrada independiente. Terraza propia con parrilla.',
    images: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=1200'],
    lat: -34.9015,
    lng: -57.9845,
    amenities: ['Terraza', 'Parrilla'],
    active: true,
    featured: false
  },
  {
    id: '9',
    title: 'Chalet Clasico Ringuelet',
    price: 240000,
    currency: 'USD',
    operation: 'Venta',
    type: 'Casa',
    neighborhood: 'Ringuelet',
    address: 'Av. 7 y 510',
    beds: 3,
    baths: 2,
    m2: 180,
    description: 'Chalet de construccion solida. Dormitorios amplios y cocina comedor.',
    images: ['https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&q=80&w=1200'],
    lat: -34.8915,
    lng: -57.9945,
    amenities: ['Garaje', 'Patio'],
    active: true,
    featured: true
  },
  {
    id: '10',
    title: 'Duplex Moderno',
    price: 165000,
    currency: 'USD',
    operation: 'Venta',
    type: 'Casa',
    neighborhood: 'Melchor Romero',
    address: 'Calle 520 y 167',
    beds: 2,
    baths: 2,
    m2: 110,
    description: 'Duplex funcional en zona tranquila. Jardin propio y espacio para auto.',
    images: ['https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=1200'],
    lat: -34.9115,
    lng: -58.0545,
    amenities: ['Jardín', 'Cochera'],
    active: true,
    featured: false
  }
];
